/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.gui.view;

/**
 *
 * @author Kevin Chuquimarca ESPE-DCCO
 */
public class FrmCinemaSystem extends javax.swing.JFrame {

    /**
     * Creates new form FrmCinemaSystem
     */
    public FrmCinemaSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        mnuMovies = new javax.swing.JMenu();
        mnuPremier = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuMovie = new javax.swing.JMenu();
        itmRecordMovie = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        mnuPromotion = new javax.swing.JMenu();
        itmRecord = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuAdmin = new javax.swing.JMenu();
        itmNewAdmin = new javax.swing.JMenuItem();
        itmUpdateAdmin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuMovies.setText("Movies");

        mnuPremier.setText("Next Premier");

        jMenuItem1.setText("Record Next Premier");
        mnuPremier.add(jMenuItem1);

        jMenuItem2.setText("Delete Next Premier");
        mnuPremier.add(jMenuItem2);

        mnuMovies.add(mnuPremier);

        mnuMovie.setText("Movie");

        itmRecordMovie.setText("Record Movie");
        itmRecordMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRecordMovieActionPerformed(evt);
            }
        });
        mnuMovie.add(itmRecordMovie);

        jMenuItem10.setText("Delete Movie");
        jMenuItem10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem10MouseClicked(evt);
            }
        });
        mnuMovie.add(jMenuItem10);

        mnuMovies.add(mnuMovie);

        jMenuBar2.add(mnuMovies);

        mnuPromotion.setText("Promotion");

        itmRecord.setText("Record Promotion");
        mnuPromotion.add(itmRecord);

        jMenuItem6.setText("Delete Promotion");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuPromotion.add(jMenuItem6);

        jMenuBar2.add(mnuPromotion);

        mnuAdmin.setText("Admin");
        mnuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAdminMouseClicked(evt);
            }
        });

        itmNewAdmin.setText("New Admin");
        mnuAdmin.add(itmNewAdmin);

        itmUpdateAdmin.setText("Updat Admin");
        itmUpdateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmUpdateAdminActionPerformed(evt);
            }
        });
        mnuAdmin.add(itmUpdateAdmin);

        jMenuBar2.add(mnuAdmin);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAdminMouseClicked
   
        
    }//GEN-LAST:event_mnuAdminMouseClicked

    private void jMenuItem10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem10MouseClicked
        this.setVisible(false);
        new FrmNextPremierInformation().setVisible(true);
    }//GEN-LAST:event_jMenuItem10MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void itmUpdateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmUpdateAdminActionPerformed

    private void itmRecordMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRecordMovieActionPerformed
        this.setVisible(false);
        new FrmNextPremierInformation().setVisible(true);
    }//GEN-LAST:event_itmRecordMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCinemaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCinemaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCinemaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCinemaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCinemaSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmNewAdmin;
    private javax.swing.JMenuItem itmRecord;
    private javax.swing.JMenuItem itmRecordMovie;
    private javax.swing.JMenuItem itmUpdateAdmin;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu mnuAdmin;
    private javax.swing.JMenu mnuMovie;
    private javax.swing.JMenu mnuMovies;
    private javax.swing.JMenu mnuPremier;
    private javax.swing.JMenu mnuPromotion;
    // End of variables declaration//GEN-END:variables
}
