/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.nextpremiers.view;

import ec.edu.nextpremiers.controller.NextMovieRegister;
import ec.edu.nextpremiers.model.NextPremier;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Kevin Chuquimarca ESPE-DCCO
 */
public class FrmCinema extends javax.swing.JFrame {

    /**
     * Creates new form FrmCinema
     */
    public FrmCinema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCinemaSystem = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pnlNextPremiers = new javax.swing.JPanel();
        pnlNextPremierMovie1 = new javax.swing.JPanel();
        lblPicture1 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblPremierDate1 = new javax.swing.JLabel();
        btnViewMore1 = new javax.swing.JButton();
        pnlNextPremierMovie2 = new javax.swing.JPanel();
        lblPicture2 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblPremierDate2 = new javax.swing.JLabel();
        btnViewMore2 = new javax.swing.JButton();
        pnlNextPremierMovie4 = new javax.swing.JPanel();
        lblPicture4 = new javax.swing.JLabel();
        lblTitle4 = new javax.swing.JLabel();
        lblPremierDate4 = new javax.swing.JLabel();
        btnViewMore4 = new javax.swing.JButton();
        pnlNextPremierMovie3 = new javax.swing.JPanel();
        lblPicture3 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        lblPremierDate3 = new javax.swing.JLabel();
        btnViewMore3 = new javax.swing.JButton();
        pnlNextPremierMovie6 = new javax.swing.JPanel();
        lblPicture6 = new javax.swing.JLabel();
        lblTitle6 = new javax.swing.JLabel();
        lblPremierDate6 = new javax.swing.JLabel();
        btnViewMore6 = new javax.swing.JButton();
        pnlNextPremierMovie5 = new javax.swing.JPanel();
        lblPicture5 = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        lblPremierDate5 = new javax.swing.JLabel();
        btnViewMore5 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPicture1.setText("jLabel11");

        lblTitle1.setText("jLabel12");

        lblPremierDate1.setText("jLabel13");

        btnViewMore1.setText("ViewMore");
        btnViewMore1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMore1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNextPremierMovie1Layout = new javax.swing.GroupLayout(pnlNextPremierMovie1);
        pnlNextPremierMovie1.setLayout(pnlNextPremierMovie1Layout);
        pnlNextPremierMovie1Layout.setHorizontalGroup(
            pnlNextPremierMovie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremierMovie1Layout.createSequentialGroup()
                .addComponent(lblPicture1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlNextPremierMovie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNextPremierMovie1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlNextPremierMovie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPremierDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(pnlNextPremierMovie1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(btnViewMore1)
                        .addGap(97, 97, 97))))
        );
        pnlNextPremierMovie1Layout.setVerticalGroup(
            pnlNextPremierMovie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremierMovie1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1)
                .addGap(18, 18, 18)
                .addComponent(lblPremierDate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewMore1)
                .addGap(30, 30, 30))
            .addComponent(lblPicture1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblPicture2.setText("jLabel15");

        lblTitle2.setText("jLabel16");

        lblPremierDate2.setText("jLabel17");

        btnViewMore2.setText("ViewMore");
        btnViewMore2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMore2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNextPremierMovie2Layout = new javax.swing.GroupLayout(pnlNextPremierMovie2);
        pnlNextPremierMovie2.setLayout(pnlNextPremierMovie2Layout);
        pnlNextPremierMovie2Layout.setHorizontalGroup(
            pnlNextPremierMovie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremierMovie2Layout.createSequentialGroup()
                .addComponent(lblPicture2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlNextPremierMovie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNextPremierMovie2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlNextPremierMovie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle2)
                            .addComponent(lblPremierDate2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNextPremierMovie2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(btnViewMore2)
                        .addGap(90, 90, 90))))
        );
        pnlNextPremierMovie2Layout.setVerticalGroup(
            pnlNextPremierMovie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPicture2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlNextPremierMovie2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle2)
                .addGap(18, 18, 18)
                .addComponent(lblPremierDate2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewMore2)
                .addGap(26, 26, 26))
        );

        lblPicture4.setText("jLabel23");

        lblTitle4.setText("jLabel24");

        lblPremierDate4.setText("jLabel25");

        btnViewMore4.setText("ViewMore");
        btnViewMore4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMore4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNextPremierMovie4Layout = new javax.swing.GroupLayout(pnlNextPremierMovie4);
        pnlNextPremierMovie4.setLayout(pnlNextPremierMovie4Layout);
        pnlNextPremierMovie4Layout.setHorizontalGroup(
            pnlNextPremierMovie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremierMovie4Layout.createSequentialGroup()
                .addComponent(lblPicture4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlNextPremierMovie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNextPremierMovie4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlNextPremierMovie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle4)
                            .addComponent(lblPremierDate4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNextPremierMovie4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(btnViewMore4)
                        .addGap(87, 87, 87))))
        );
        pnlNextPremierMovie4Layout.setVerticalGroup(
            pnlNextPremierMovie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPicture4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlNextPremierMovie4Layout.createSequentialGroup()
                .addComponent(lblTitle4)
                .addGap(18, 18, 18)
                .addComponent(lblPremierDate4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewMore4)
                .addGap(40, 40, 40))
        );

        lblPicture3.setText("jLabel19");

        lblTitle3.setText("jLabel20");

        lblPremierDate3.setText("jLabel21");

        btnViewMore3.setText("ViewMore");
        btnViewMore3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMore3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNextPremierMovie3Layout = new javax.swing.GroupLayout(pnlNextPremierMovie3);
        pnlNextPremierMovie3.setLayout(pnlNextPremierMovie3Layout);
        pnlNextPremierMovie3Layout.setHorizontalGroup(
            pnlNextPremierMovie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremierMovie3Layout.createSequentialGroup()
                .addComponent(lblPicture3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlNextPremierMovie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNextPremierMovie3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlNextPremierMovie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle3)
                            .addComponent(lblPremierDate3)))
                    .addGroup(pnlNextPremierMovie3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnViewMore3)))
                .addGap(0, 97, Short.MAX_VALUE))
        );
        pnlNextPremierMovie3Layout.setVerticalGroup(
            pnlNextPremierMovie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPicture3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlNextPremierMovie3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle3)
                .addGap(18, 18, 18)
                .addComponent(lblPremierDate3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewMore3)
                .addGap(33, 33, 33))
        );

        lblPicture6.setText("jLabel28");

        lblTitle6.setText("jLabel32");

        lblPremierDate6.setText("jLabel33");

        btnViewMore6.setText("ViewMore");
        btnViewMore6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMore6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNextPremierMovie6Layout = new javax.swing.GroupLayout(pnlNextPremierMovie6);
        pnlNextPremierMovie6.setLayout(pnlNextPremierMovie6Layout);
        pnlNextPremierMovie6Layout.setHorizontalGroup(
            pnlNextPremierMovie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremierMovie6Layout.createSequentialGroup()
                .addComponent(lblPicture6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlNextPremierMovie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNextPremierMovie6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlNextPremierMovie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle6)
                            .addComponent(lblPremierDate6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNextPremierMovie6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(btnViewMore6)
                        .addGap(79, 79, 79))))
        );
        pnlNextPremierMovie6Layout.setVerticalGroup(
            pnlNextPremierMovie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPicture6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlNextPremierMovie6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle6)
                .addGap(18, 18, 18)
                .addComponent(lblPremierDate6)
                .addGap(43, 43, 43)
                .addComponent(btnViewMore6)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        lblPicture5.setText("jLabel27");

        lblTitle5.setText("jLabel29");

        lblPremierDate5.setText("jLabel30");

        btnViewMore5.setText("ViewMore");
        btnViewMore5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMore5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNextPremierMovie5Layout = new javax.swing.GroupLayout(pnlNextPremierMovie5);
        pnlNextPremierMovie5.setLayout(pnlNextPremierMovie5Layout);
        pnlNextPremierMovie5Layout.setHorizontalGroup(
            pnlNextPremierMovie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremierMovie5Layout.createSequentialGroup()
                .addComponent(lblPicture5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlNextPremierMovie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNextPremierMovie5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlNextPremierMovie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle5)
                            .addComponent(lblPremierDate5)))
                    .addGroup(pnlNextPremierMovie5Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnViewMore5)))
                .addGap(0, 89, Short.MAX_VALUE))
        );
        pnlNextPremierMovie5Layout.setVerticalGroup(
            pnlNextPremierMovie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPicture5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlNextPremierMovie5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle5)
                .addGap(18, 18, 18)
                .addComponent(lblPremierDate5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewMore5)
                .addGap(32, 32, 32))
        );

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout pnlNextPremiersLayout = new javax.swing.GroupLayout(pnlNextPremiers);
        pnlNextPremiers.setLayout(pnlNextPremiersLayout);
        pnlNextPremiersLayout.setHorizontalGroup(
            pnlNextPremiersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremiersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNextPremiersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNextPremiersLayout.createSequentialGroup()
                        .addGroup(pnlNextPremiersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNextPremiersLayout.createSequentialGroup()
                                .addComponent(pnlNextPremierMovie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNextPremiersLayout.createSequentialGroup()
                                .addComponent(pnlNextPremierMovie5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNextPremiersLayout.createSequentialGroup()
                                .addComponent(pnlNextPremierMovie3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlNextPremiersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNextPremiersLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlNextPremierMovie6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(pnlNextPremiersLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlNextPremiersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlNextPremierMovie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlNextPremierMovie4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(14, Short.MAX_VALUE))))
                    .addGroup(pnlNextPremiersLayout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlNextPremiersLayout.createSequentialGroup()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlNextPremiersLayout.setVerticalGroup(
            pnlNextPremiersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremiersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNextPremiersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlNextPremierMovie2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNextPremierMovie1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNextPremiersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(pnlNextPremierMovie4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNextPremierMovie3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNextPremiersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(pnlNextPremierMovie6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNextPremierMovie5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlNextPremiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlNextPremiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlCinemaSystem.addTab("NextPremiers", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCinemaSystem))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCinemaSystem))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMore1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMore1MouseClicked
        FrmMovie frmMovie = new FrmMovie();
        try {
            frmMovie.showMovie(showDataMovie().get(0));
        } catch (IOException ex) {
            Logger.getLogger(FrmCinema.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnViewMore1MouseClicked

    private void btnViewMore2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMore2MouseClicked
         FrmMovie frmMovie = new FrmMovie();
        try {
            frmMovie.showMovie(showDataMovie().get(1));
        } catch (IOException ex) {
            Logger.getLogger(FrmCinema.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnViewMore2MouseClicked

    private void btnViewMore3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMore3MouseClicked
        FrmMovie frmMovie = new FrmMovie();
        try {
            frmMovie.showMovie(showDataMovie().get(2));
        } catch (IOException ex) {
            Logger.getLogger(FrmCinema.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnViewMore3MouseClicked

    private void btnViewMore4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMore4MouseClicked
        FrmMovie frmMovie = new FrmMovie();
        try {
            frmMovie.showMovie(showDataMovie().get(3));
        } catch (IOException ex) {
            Logger.getLogger(FrmCinema.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnViewMore4MouseClicked

    private void btnViewMore5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMore5MouseClicked
         FrmMovie frmMovie = new FrmMovie();
        try {
            frmMovie.showMovie(showDataMovie().get(4));
        } catch (IOException ex) {
            Logger.getLogger(FrmCinema.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnViewMore5MouseClicked

    private void btnViewMore6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMore6MouseClicked
         FrmMovie frmMovie = new FrmMovie();
        try {
            frmMovie.showMovie(showDataMovie().get(5));
        } catch (IOException ex) {
            Logger.getLogger(FrmCinema.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnViewMore6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCinema().setVisible(true);
            }
        });
    }

    public ArrayList<NextPremier> showDataMovie() throws IOException {
        NextMovieRegister movieRegister = new NextMovieRegister();
        ArrayList<NextPremier> movies;
        movies = movieRegister.createMovieList();
        
        lblPicture1.setIcon(showPicture(movies.get(0).getNamePicture()));
        lblPicture2.setIcon(showPicture(movies.get(1).getNamePicture()));
        lblPicture3.setIcon(showPicture(movies.get(2).getNamePicture()));
        lblPicture4.setIcon(showPicture(movies.get(3).getNamePicture()));
        lblPicture5.setIcon(showPicture(movies.get(4).getNamePicture()));
        lblPicture6.setIcon(showPicture(movies.get(5).getNamePicture()));
        
        lblTitle1.setText(movies.get(0).getTitle());
        lblTitle2.setText(movies.get(1).getTitle());
        lblTitle3.setText(movies.get(2).getTitle());
        lblTitle4.setText(movies.get(3).getTitle());
        lblTitle5.setText(movies.get(4).getTitle());
        lblTitle6.setText(movies.get(5).getTitle());

        lblPremierDate1.setText(movies.get(0).getPremierDate());
        lblPremierDate2.setText(movies.get(1).getPremierDate());
        lblPremierDate3.setText(movies.get(2).getPremierDate());
        lblPremierDate4.setText(movies.get(3).getPremierDate());
        lblPremierDate5.setText(movies.get(4).getPremierDate());
        lblPremierDate6.setText(movies.get(5).getPremierDate());
        return movies;
    }
    
    public ImageIcon showPicture(String namePicture){
        ImageIcon image = new ImageIcon(getClass().getResource("/pictures/" + namePicture));
        ImageIcon icon = new ImageIcon(image.getImage().getScaledInstance(110, 170, Image.SCALE_DEFAULT));
        return icon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewMore1;
    private javax.swing.JButton btnViewMore2;
    private javax.swing.JButton btnViewMore3;
    private javax.swing.JButton btnViewMore4;
    private javax.swing.JButton btnViewMore5;
    private javax.swing.JButton btnViewMore6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblPicture1;
    private javax.swing.JLabel lblPicture2;
    private javax.swing.JLabel lblPicture3;
    private javax.swing.JLabel lblPicture4;
    private javax.swing.JLabel lblPicture5;
    private javax.swing.JLabel lblPicture6;
    private javax.swing.JLabel lblPremierDate1;
    private javax.swing.JLabel lblPremierDate2;
    private javax.swing.JLabel lblPremierDate3;
    private javax.swing.JLabel lblPremierDate4;
    private javax.swing.JLabel lblPremierDate5;
    private javax.swing.JLabel lblPremierDate6;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JTabbedPane pnlCinemaSystem;
    private javax.swing.JPanel pnlNextPremierMovie1;
    private javax.swing.JPanel pnlNextPremierMovie2;
    private javax.swing.JPanel pnlNextPremierMovie3;
    private javax.swing.JPanel pnlNextPremierMovie4;
    private javax.swing.JPanel pnlNextPremierMovie5;
    private javax.swing.JPanel pnlNextPremierMovie6;
    private javax.swing.JPanel pnlNextPremiers;
    // End of variables declaration//GEN-END:variables
}
